CREATE TABLE `irpf_forms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int,
	`nome_cliente` varchar(255) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`data_nascimento` varchar(10) NOT NULL,
	`email` varchar(320) NOT NULL,
	`telefone` varchar(20),
	`numero_processo` varchar(50) NOT NULL,
	`vara` varchar(100) NOT NULL,
	`comarca` varchar(100) NOT NULL,
	`fonte_pagadora` varchar(255) NOT NULL,
	`cnpj` varchar(18) NOT NULL,
	`bruto_homologado` int NOT NULL,
	`tributavel_homologado` int NOT NULL,
	`numero_meses` int NOT NULL,
	`alvara_valor` int NOT NULL,
	`alvara_data` varchar(10) NOT NULL,
	`darf_valor` int NOT NULL,
	`darf_data` varchar(10) NOT NULL,
	`honorarios_valor` int NOT NULL,
	`honorarios_ano` varchar(4) NOT NULL,
	`proporcao` varchar(20) NOT NULL,
	`rendimentos_tributavel_alvara` int NOT NULL,
	`rendimentos_tributavel_honorarios` int NOT NULL,
	`base_calculo` int NOT NULL,
	`rra` varchar(20) NOT NULL,
	`ir_mensal` varchar(20) NOT NULL,
	`ir_devido` int NOT NULL,
	`irpf_restituir` int NOT NULL,
	`status_pagamento` enum('pendente','pago','cancelado') NOT NULL DEFAULT 'pendente',
	`tipo_acesso` enum('free','pago') NOT NULL DEFAULT 'pago',
	`categoria` enum('free','starter','builder','specialist') NOT NULL DEFAULT 'starter',
	`data_pagamento` timestamp,
	`data_agendamento_email` timestamp,
	`status_email` enum('pendente','agendado','enviado','erro') DEFAULT 'pendente',
	`status_kit_ir` enum('nao_solicitado','pendente','pago','enviado','cancelado') NOT NULL DEFAULT 'nao_solicitado',
	`data_pagamento_kit` timestamp,
	`data_envio_kit` timestamp,
	`status_envio_kit` enum('pendente','agendado','enviado','erro') DEFAULT 'pendente',
	`pdf_planilha_url` text,
	`pdf_esclarecimentos_url` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `irpf_forms_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`form_id` int NOT NULL,
	`conteudo` text NOT NULL,
	`criado_em` timestamp NOT NULL DEFAULT (now()),
	`atualizado_em` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `selic_table` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ano` int NOT NULL,
	`mes` int NOT NULL,
	`taxa` varchar(20) NOT NULL,
	`acumulada` varchar(20) NOT NULL,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `selic_table_id` PRIMARY KEY(`id`)
);
